title: Alireza Nasiri
logo: /my_images/my_pic.jpg
description: PhD Candidate in Computer Science and Engineering at University of South Carolina
resume: /afa/afads.pdf
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
